DROP SCHEMA IF EXISTS COACHIFY CASCADE;
CREATE SCHEMA COACHIFY;

CREATE TABLE IF NOT EXISTS COACHIFY.User(
        user_id SERIAL NOT NULL,
        name VARCHAR(20) NOT NULL,
        PRIMARY KEY(user_id));